### ISSUE TITLE
Error with parser.py

### ISSUE THREAD

**Issue by TimeEscaper** [RobotiXX/MuSoHu-data-collection#2]
Dear authors,

Thanks for releasing awesome dataset. I am trying to parse rosbags using parser.py script, as suggested in Readme, and getting following error:

`Traceback (most recent call last):
  File "parser.py", line 11, in <module>
    from utils.helpers import get_conf
ModuleNotFoundError: No module named 'utils'`

Seems there is a missing module. Can you help to tackle this issue?

**Comment by mhnazeri** [comment]
Hi,

Thanks for reaching out and raising the issue. We fixed the import issue. Can you pull the changes and try again?

**Comment by TimeEscaper** [comment]
Dear authors,

Sorry for very late response, managed to test it only just now. It works well right now, after applying your fix and installing some additional dependencies I managed to launch parser. If there will be more issues, I will notify you.

Thanks for your help!
